sudo: required
services:
  - docker
before_install:
  - docker build -t travis/docker_frontend -f Dockerfile.dev .  
script:
  - docker run --name docker_fn travis/docker_frontend npm run test -- --coverage
